include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # Add custom linter rules here
  
analyzer:
  errors:
    # Ignore specific errors in the example app
    use_build_context_synchronously: ignore
