name: flutter_cache_maestro
description: A Flutter plugin for caching data from various types of links (images, videos, audio, documents) with customizable storage options.
version: 0.1.6
homepage: https://github.com/kibukamusoke/flutter_cache_maestro

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  path_provider: ^2.0.2
  path: ^1.8.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
